# Generated by Django 2.0 on 2020-06-11 17:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('news', '0004_auto_20200611_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
