# Generated by Django 2.0 on 2020-06-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200603_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('created',)},
        ),
    ]
