# Generated by Django 2.2 on 2020-06-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
