# Generated by Django 2.2 on 2020-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200810_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
