# Generated by Django 2.2.15 on 2020-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20200823_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
