# Generated by Django 2.2.15 on 2020-09-25 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20200925_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon musi mieć format: '+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
