# Generated by Django 2.2 on 2020-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0011_auto_20200823_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='steps',
            new_name='step1',
        ),
        migrations.AddField(
            model_name='recipe',
            name='step2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step4',
            field=models.TextField(blank=True),
        ),
    ]
