# Generated by Django 2.2.15 on 2020-09-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0013_auto_20200829_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
