# Generated by Django 3.1.3 on 2021-02-14 11:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0019_auto_20200925_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description_of_diet', models.TextField(blank=True)),
                ('amount_of_breakfast', models.IntegerField(default=1)),
                ('breakfast_time', models.TimeField(blank=True)),
                ('amount_of_lunch', models.IntegerField(default=1)),
                ('lunch_time', models.TimeField(blank=True)),
                ('second_lunch_time', models.TimeField(blank=True, null=True)),
                ('amount_of_dinner', models.IntegerField(default=1)),
                ('dinner_time', models.TimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_subscribe', models.DateField(default=datetime.date.today)),
                ('breakfast', models.ManyToManyField(blank=True, related_name='breakfast', to='recipes.Recipe')),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner', to='recipes.Recipe')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch', to='recipes.Recipe')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
