# Generated by Django 2.2 on 2020-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_auto_20200625_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
