# Generated by Django 2.2 on 2020-08-07 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diets', '0006_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='user',
        ),
        migrations.AddField(
            model_name='diet',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
