# Generated by Django 2.2 on 2020-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0008_auto_20200619_1732'),
        ('diets', '0007_auto_20200807_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='breakfast',
        ),
        migrations.AddField(
            model_name='diet',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast', to='hairstyle.Recipe'),
        ),
    ]
