# Generated by Django 2.2 on 2020-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0012_auto_20200808_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
