# Generated by Django 2.2 on 2020-08-12 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diets', '0017_auto_20200812_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='diet',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
