# Generated by Django 2.2 on 2020-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0018_auto_20200812_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='phone',
        ),
        migrations.AddField(
            model_name='diet',
            name='amount_of_breakfast',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diet',
            name='amount_of_dinner',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diet',
            name='amount_of_lunch',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diet',
            name='description_of_diet',
            field=models.TextField(blank=True),
        ),
    ]
