# Generated by Django 2.2 on 2020-08-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200810_1008'),
        ('diets', '0021_auto_20200814_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='lunch',
        ),
        migrations.AddField(
            model_name='diet',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='recipes.Recipe'),
        ),
    ]
