# Generated by Django 2.2 on 2020-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200810_1008'),
        ('diets', '0022_auto_20200814_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='lunch',
        ),
        migrations.AddField(
            model_name='diet',
            name='lunch',
            field=models.ManyToManyField(blank=True, null=True, related_name='lunch', to='recipes.Recipe'),
        ),
    ]
