# Generated by Django 2.2 on 2020-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0023_auto_20200814_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch', to='recipes.Recipe'),
        ),
    ]
