# Generated by Django 2.2 on 2020-08-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0010_auto_20200810_1008'),
        ('diets', '0025_auto_20200814_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='lunch',
        ),
        migrations.AddField(
            model_name='diet',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch', to='hairstyle.Recipe'),
        ),
    ]
