# Generated by Django 2.2 on 2020-08-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200810_1008'),
        ('diets', '0026_auto_20200814_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='dinner',
        ),
        migrations.AddField(
            model_name='diet',
            name='dinner',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.RemoveField(
            model_name='diet',
            name='lunch',
        ),
        migrations.AddField(
            model_name='diet',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='recipes.Recipe'),
        ),
    ]
