# Generated by Django 2.2 on 2020-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0028_auto_20200817_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='second_lunch_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
