# Generated by Django 2.2 on 2020-08-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0030_diet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
