# Generated by Django 2.2 on 2020-08-19 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0031_auto_20200818_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='date_subscribe',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
